Gobstones CLI
mumuki/rungs pull request #1
Opened 2016-12-02 18:10 UTC by rodri042

@flbulgarelli 
What do you think about renaming & moving this to gobstones/gs-weblang-cli?
Does the `--ast` option cover your needs at Mulang?

2016-12-02 18:12 UTC, flbulgarelli commented
> What do you think about renaming & moving this to gobstones/gs-weblang-cli?

Its ok for me

2016-12-02 18:21 UTC, flbulgarelli requested changes
Could we add some tests?

I mean, I it is not a hard request, but a nice to have

2016-12-02 18:21 UTC, flbulgarelli commented on README.md
> +git clone https://github.com/gobstones/gs-weblang-cli gobs
@rodri042 I would rename the executable to name gs-weblang-cli.

2016-12-02 18:21 UTC, flbulgarelli commented on README.md
> +gobs --ast /tmp/gobs.gbs
I really need to avoid writing a file. Can this input be read from `stdin`?

2016-12-02 18:21 UTC, flbulgarelli commented on README.md
> +gobs --ast /tmp/gobs.gbs
I mean, I am not against having a file input option, but default should still be reading from `stdin`

2016-12-02 20:22 UTC, flbulgarelli commented on test/run-spec.js
> +    });
You rock!

2016-12-03 01:43 UTC, rodri042 commented on README.md
> +gobs --ast /tmp/gobs.gbs
Done. Now it can be executed like this: `echo "program {\n Poner(Azul)\n }" | gs-weblang-cli --ast --from_stdin`

2016-12-03 01:43 UTC, rodri042 commented
I'll close the PR, add a CI and migrate this to https://github.com/gobstones/gs-weblang-cli

2016-12-03 01:43 UTC, closed without merging